module.exports = [
  { prop: 'animation', value: 'none 0s ease 0s 1 normal none running' },
  { prop: 'backface-visibility', value: 'visible' },
  { prop: 'background', value: 'transparent none repeat 0% 0% / auto auto padding-box border-box scroll' },
  { prop: 'border', value: 'medium none currentColor' },
  { prop: 'border-radius', value: '0' },
  { prop: 'border-collapse', value: 'separate' },
  { prop: 'border-image', value: 'none' },
  { prop: 'border-spacing', value: '0' },
  { prop: 'bottom', value: 'auto' },
  { prop: 'box-shadow', value: 'none' },
  { prop: 'box-sizing', value: 'content-box' },
  { prop: 'caption-side', value: 'top' },
  { prop: 'clear', value: 'none' },
  { prop: 'clip', value: 'auto' },
  { prop: 'color', value: 'inherit' },
  { prop: 'columns', value: 'auto' },
  { prop: 'column-count', value: 'auto' },
  { prop: 'column-fill', value: 'balance' },
  { prop: 'column-gap', value: 'normal' },
  { prop: 'column-rule', value: 'medium none currentColor' },
  { prop: 'column-rule-color', value: 'currentColor' },
  { prop: 'column-rule-style', value: 'none' },
  { prop: 'column-rule-width', value: 'none' },
  { prop: 'column-span', value: '1' },
  { prop: 'column-width', value: 'auto' },
  { prop: 'content', value: 'normal' },
  { prop: 'counter-increment', value: 'none' },
  { prop: 'counter-reset', value: 'none' },
  { prop: 'cursor', value: 'auto' },
  { prop: 'direction', value: 'ltr' },
  { prop: 'display', value: 'inline' },
  { prop: 'empty-cells', value: 'show' },
  { prop: 'float', value: 'none' },
  { prop:  'font',
    value: 'normal normal normal normal medium normal sans-serif' },
  { prop: 'height', value: 'auto' },
  { prop: 'hyphens', value: 'none' },
  { prop: 'left', value: 'auto' },
  { prop: 'letter-spacing', value: 'normal' },
  { prop: 'line-height', value: 'normal' },
  { prop: 'list-style', value: 'none' },
  { prop: 'list-style-image', value: 'none' },
  { prop: 'list-style-position', value: 'outside' },
  { prop: 'list-style-type', value: 'disc' },
  { prop: 'margin', value: '0' },
  { prop: 'max-height', value: 'none' },
  { prop: 'max-width', value: 'none' },
  { prop: 'min-height', value: '0' },
  { prop: 'min-width', value: '0' },
  { prop: 'opacity', value: '1' },
  { prop: 'orphans', value: '0' },
  { prop: 'outline', value: '0' },
  { prop: 'outline-color', value: 'invert' },
  { prop: 'outline-style', value: 'none' },
  { prop: 'outline-width', value: 'medium' },
  { prop: 'overflow', value: 'visible' },
  { prop: 'overflow-x', value: 'visible' },
  { prop: 'overflow-y', value: 'visible' },
  { prop: 'padding', value: '0' },
  { prop: 'page-break-after', value: 'auto' },
  { prop: 'page-break-before', value: 'auto' },
  { prop: 'page-break-inside', value: 'auto' },
  { prop: 'perspective', value: 'none' },
  { prop: 'perspective-origin', value: '50% 50%' },
  { prop: 'position', value: 'static' },
  { prop: 'right', value: 'auto' },
  { prop: 'tab-size', value: '8' },
  { prop: 'table-layout', value: 'auto' },
  { prop: 'text-align', value: 'inherit' },
  { prop: 'text-align-last', value: 'auto' },
  { prop: 'text-decoration', value: 'none' },
  { prop: 'text-decoration-color', value: 'inherit' },
  { prop: 'text-decoration-line', value: 'none' },
  { prop: 'text-decoration-style', value: 'solid' },
  { prop: 'text-indent', value: '0' },
  { prop: 'text-shadow', value: 'none' },
  { prop: 'text-transform', value: 'none' },
  { prop: 'top', value: 'auto' },
  { prop: 'transform', value: 'none' },
  { prop: 'transform-style', value: 'flat' },
  { prop: 'transition', value: 'none' },
  { prop: 'transition-delay', value: '0s' },
  { prop: 'transition-duration', value: '0s' },
  { prop: 'transition-property', value: 'none' },
  { prop: 'transition-timing-function', value: 'ease' },
  { prop: 'unicode-bidi', value: 'normal' },
  { prop: 'vertical-align', value: 'baseline' },
  { prop: 'visibility', value: 'visible' },
  { prop: 'white-space', value: 'normal' },
  { prop: 'widows', value: '0' },
  { prop: 'width', value: 'auto' },
  { prop: 'word-spacing', value: 'normal' },
  { prop: 'z-index', value: 'auto' }
];
